// Demo data for simulation

export interface Repo {
  id: string;
  org_id: string;
  provider: 'github' | 'demo';
  owner: string;
  name: string;
  default_branch: string;
  created_at: string;
  last_run?: DojoRun;
}

export interface DojoCheck {
  id: string;
  name: string;
  description: string;
  enabled: boolean;
  required?: boolean;
}

export interface DojoRun {
  id: string;
  repo_id: string;
  status: 'queued' | 'running' | 'awaiting_approval' | 'completed' | 'failed';
  created_at: string;
  started_at?: string;
  finished_at?: string;
  pr_url?: string;
  ci_url?: string;
  preview_url?: string;
  shipdojo_score?: number;
  current_step?: number;
  report_md?: string;
}

export interface DojoEvent {
  id: string;
  run_id: string;
  ts: string;
  level: 'info' | 'warn' | 'error';
  step: number;
  message: string;
  meta?: Record<string, unknown>;
}

export const DEFAULT_CHECKS: DojoCheck[] = [
  {
    id: 'pr-only',
    name: 'PR-only changes',
    description: 'All modifications happen through pull requests',
    enabled: true,
    required: true
  },
  {
    id: 'dojo-gate',
    name: 'Require Dojo Gate approval',
    description: 'Human-in-the-loop approval before merge',
    enabled: true
  },
  {
    id: 'rate-limiting',
    name: 'Add rate limiting template',
    description: 'Add API rate limiting middleware',
    enabled: true
  },
  {
    id: 'auth-hardening',
    name: 'Add auth hardening checklist',
    description: 'Security checklist for authentication',
    enabled: true
  },
  {
    id: 'db-migration',
    name: 'Add DB migration sanity checks',
    description: 'Validate database migrations before running',
    enabled: true
  },
  {
    id: 'ci-workflow',
    name: 'Add basic CI workflow',
    description: 'GitHub Actions for testing and building',
    enabled: true
  },
  {
    id: 'security-linting',
    name: 'Add security linting',
    description: 'Static analysis for security vulnerabilities',
    enabled: true
  },
  {
    id: 'playwright-tests',
    name: 'Create Playwright smoke tests',
    description: 'End-to-end browser tests',
    enabled: false
  },
  {
    id: 'shipdojo-report',
    name: 'Generate ShipDojo Report',
    description: 'Detailed report of all changes and improvements',
    enabled: true
  },
  {
    id: 'shipdojo-score',
    name: 'Compute ShipDojo Score',
    description: 'Production-readiness score',
    enabled: true
  }
];

export const RUN_STEPS = [
  { step: 1, name: 'Detecting stack', duration: 2000 },
  { step: 2, name: 'Generating env template', duration: 1500 },
  { step: 3, name: 'Adding CI workflow', duration: 2000 },
  { step: 4, name: 'Auth/rate-limit hardening', duration: 2500 },
  { step: 5, name: 'Migration checks', duration: 1500 },
  { step: 6, name: 'Running tests', duration: 3000 },
  { step: 7, name: 'Opening PR', duration: 1000 },
  { step: 8, name: 'Awaiting Dojo Gate approval', duration: 0 }, // Waits for user
  { step: 9, name: 'Merging & deploying', duration: 2000 },
  { step: 10, name: 'Generating report', duration: 1500 }
];

export function createDemoRepo(orgId: string): Repo {
  return {
    id: `demo-repo-${Date.now()}`,
    org_id: orgId,
    provider: 'demo',
    owner: 'shipdojo',
    name: 'demo-vibecoded-app',
    default_branch: 'main',
    created_at: new Date().toISOString()
  };
}

export function generateReportMarkdown(score: number, checks: DojoCheck[]): string {
  const enabledChecks = checks.filter(c => c.enabled);
  const passedChecks = enabledChecks.length;
  
  return `# ShipDojo Report

## Summary

**ShipDojo Score: ${score}/100**

Your repository has been productionized with ${passedChecks} checks applied.

## Changes Made

### Security Hardening
- ✅ Added rate limiting middleware
- ✅ Implemented auth best practices checklist
- ✅ Security linting configured

### CI/CD Pipeline
- ✅ GitHub Actions workflow added
- ✅ Test automation configured
- ✅ Build verification enabled

### Database
- ✅ Migration sanity checks added
- ✅ Schema validation configured

### Documentation
- ✅ Environment template created (.env.example)
- ✅ README updated with setup instructions

## Recommendations

1. Consider adding Playwright smoke tests for critical user flows
2. Set up monitoring and alerting for production
3. Enable branch protection rules on main branch
4. Configure automated dependency updates

## Next Steps

Your code is now production-ready! Deploy with confidence using the preview URL, then promote to production when ready.

---

*Generated by ShipDojo on ${new Date().toLocaleDateString()}*
`;
}

// Storage helpers for demo mode
export function getDemoRepos(): Repo[] {
  const repos = localStorage.getItem('shipdojo_repos');
  return repos ? JSON.parse(repos) : [];
}

export function saveDemoRepos(repos: Repo[]) {
  localStorage.setItem('shipdojo_repos', JSON.stringify(repos));
}

export function getDemoRuns(): DojoRun[] {
  const runs = localStorage.getItem('shipdojo_runs');
  return runs ? JSON.parse(runs) : [];
}

export function saveDemoRuns(runs: DojoRun[]) {
  localStorage.setItem('shipdojo_runs', JSON.stringify(runs));
}

export function getDemoEvents(): DojoEvent[] {
  const events = localStorage.getItem('shipdojo_events');
  return events ? JSON.parse(events) : [];
}

export function saveDemoEvents(events: DojoEvent[]) {
  localStorage.setItem('shipdojo_events', JSON.stringify(events));
}

export function getDemoChecks(): DojoCheck[] {
  const checks = localStorage.getItem('shipdojo_checks');
  return checks ? JSON.parse(checks) : DEFAULT_CHECKS;
}

export function saveDemoChecks(checks: DojoCheck[]) {
  localStorage.setItem('shipdojo_checks', JSON.stringify(checks));
}
